/**
 * 성향 테스트 12문항 — docs/planning/personality_questions_seed_ko.csv에서 생성(수정은 CSV에서).
 * A=음수 방향(-25), B=양수 방향(+25). UI는 2지선다, 엔진은 5단계(±25/±12.5/0) 허용.
 */
import type { Question } from './types';

export const QUESTIONS: readonly Question[] = [
  {
    id: 'Q001',
    order: 1,
    axis: 'physical',
    prompt: '쉬는 날 새로운 활동을 한다면 어느 쪽이 더 끌리나요',
    choiceA: '마음이 차분해지는 조용한 활동',
    choiceB: '에너지가 생기는 활동적인 활동',
    weight: 1,
  },
  {
    id: 'Q002',
    order: 2,
    axis: 'physical',
    prompt: '어떤 장면이 더 편안하게 느껴지나요',
    choiceA: '앉아서 한 가지 일에 집중하는 장면',
    choiceB: '돌아다니거나 몸을 움직이는 장면',
    weight: 1,
  },
  {
    id: 'Q003',
    order: 3,
    axis: 'relation',
    prompt: '처음 해보는 활동에 참여한다면 어느 쪽이 더 좋나요',
    choiceA: '혼자 또는 아주 소수로 조용히 해보기',
    choiceB: '비슷한 관심사를 가진 사람들과 함께 해보기',
    weight: 1,
  },
  {
    id: 'Q004',
    order: 4,
    axis: 'relation',
    prompt: '어떤 분위기라면 더 참여하고 싶을까요',
    choiceA: '각자 자기 속도대로 편하게 즐기는 분위기',
    choiceB: '서로 자연스럽게 대화하고 알아가는 분위기',
    weight: 1,
  },
  {
    id: 'Q005',
    order: 5,
    axis: 'experience',
    prompt: '활동 중 어떤 순간이 더 만족스럽나요',
    choiceA: '보고 듣고 느끼며 감상하는 순간',
    choiceB: '직접 만들고 연습하고 해보는 순간',
    weight: 1,
  },
  {
    id: 'Q006',
    order: 6,
    axis: 'experience',
    prompt: '둘 중 하나를 고른다면 어떤 활동을 선택하시겠나요',
    choiceA: '해설이 있는 전시 또는 음악 감상',
    choiceB: '직접 만들거나 연습하는 워크숍',
    weight: 1,
  },
  {
    id: 'Q007',
    order: 7,
    axis: 'satisfaction',
    prompt: '활동이 끝났을 때 어떤 기분이 더 좋나요',
    choiceA: '하는 동안의 시간과 과정이 좋았다',
    choiceB: '무언가 만들었거나 뚜렷한 결과를 얻었다',
    weight: 1,
  },
  {
    id: 'Q008',
    order: 8,
    axis: 'satisfaction',
    prompt: '어떤 만족감이 더 중요한가요',
    choiceA: '활동하는 동안 편안하게 몰입하는 것',
    choiceB: '눈에 보이는 발전이나 완성물을 얻는 것',
    weight: 1,
  },
  {
    id: 'Q009',
    order: 9,
    axis: 'value',
    prompt: '취미를 고를 때 어떤 가치가 더 중요한가요',
    choiceA: '감정과 취향과 나만의 분위기를 채워주는 것',
    choiceB: '실생활에 바로 도움이 되는 것',
    weight: 1,
  },
  {
    id: 'Q010',
    order: 10,
    axis: 'value',
    prompt: '어떤 활동이 더 끌리나요',
    choiceA: '꽃과 향과 미술과 음악처럼 감성을 채우는 활동',
    choiceB: '요리와 디지털 활용과 건강과 집 관리처럼 실용적인 활동',
    weight: 1,
  },
  {
    id: 'Q011',
    order: 11,
    axis: 'novelty',
    prompt: '여가 활동을 하나 선택한다면 어느 방향을 선호하시나요',
    choiceA: '익숙한 활동을 조금 새롭게 즐기기',
    choiceB: '한 번도 해보지 않은 활동을 경험하기',
    weight: 1,
  },
  {
    id: 'Q012',
    order: 12,
    axis: 'depth',
    prompt: '마음에 드는 활동을 찾았다면 어떤 방식으로 즐기고 싶나요',
    choiceA: '부담 없이 한 번 가볍게 체험하기',
    choiceB: '꾸준히 배우며 깊게 즐기기',
    weight: 1,
  },
] as const;
